CLASS zbp2_ad_i_online_shop DEFINITION PUBLIC ABSTRACT FINAL FOR BEHAVIOR OF zad_i_online_shop.
class-DATA cv_pr_mapped TYPE RESPONSE FOR MAPPED i_purchaserequisitiontp.
class-DATA cv_po_mapped TYPE RESPONSE FOR MAPPED I_PurchaseOrderTP_2.
ENDCLASS.



CLASS ZBP2_AD_I_ONLINE_SHOP IMPLEMENTATION.
ENDCLASS.
